import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/main-header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-100 text-slate-800`}
      >
        <Header />
        <main
          className="
          w-full mx-auto 
          px-4 md:px-6 
          /* ✅ 모바일(기본): w-full */
          /* ✅ 태블릿(md): 744px 고정 (시안 맞춤) */
          md:max-w-186
          /* ✅ 데스크탑(xl): 1200px로 확장 (시안 맞춤) */
          xl:max-w-300
          py-6 md:py-10
        "
        >
          {children}
        </main>
      </body>
    </html>
  );
}
